server {
    listen       80;
    server_name  localhost;
    root         /var/www/html/public;
    index        index.php;

    client_max_body_size 100M;

    # Main routing (Laravel/Modern apps)
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # PHP handling (secure)
    location ~ \.php$ {
        try_files            $uri =404;
        fastcgi_pass         app:9000;
        include              fastcgi_params;
        fastcgi_param        SCRIPT_FILENAME  $document_root$fastcgi_script_name;
        fastcgi_param        DOCUMENT_ROOT  $realpath_root;

        fastcgi_buffers      16 16k;
        fastcgi_buffer_size  32k;
    }

    # protect access to hidden files (.env, .git, etc)
    location ~/\.(?!well-known).* {
        deny    all;
    }

    # Disables access to sensitives files
    location ~* \.(env|log|ini)$ {
        deny    all;
    }

    # Static assets optimisation
    location ~* \.(jpg|jpeg|png|gif|ico|css|js|svg|woff|woff2|ttf|eot)$ {
        expires     7d;
        access_log  off;
        add_header  Cache-Control "public";
    }
}